#!/usr/bin/env bash
# =============================================================================
# 00_setup.sh — One-time environment setup for KV Cache Compression experiments
#
# Usage:
#   bash 00_setup.sh --model_path /path/to/Meta-Llama-3-8B-Instruct
#
# Requirements:
#   - CUDA-enabled GPU with ≥24GB VRAM (A100-40G or A6000 recommended)
#   - Python 3.10+
#   - Internet access for HuggingFace data download
# =============================================================================
set -euo pipefail

# ── Parse arguments ────────────────────────────────────────────────────────────
MODEL_PATH=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --model_path) MODEL_PATH="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [[ -z "$MODEL_PATH" ]]; then
    echo "Usage: bash 00_setup.sh --model_path /path/to/Meta-Llama-3-8B-Instruct"
    exit 1
fi

echo "======================================================"
echo "  KV Cache Compression Experiments — Setup"
echo "======================================================"
echo "Model path : $MODEL_PATH"
echo ""

# ── Step 1: Clone KVCache-Factory ──────────────────────────────────────────────
REPO_DIR="./KVCache-Factory"
if [[ ! -d "$REPO_DIR" ]]; then
    echo "[1/5] Cloning KVCache-Factory..."
    git clone https://github.com/Zefan-Cai/KVCache-Factory.git "$REPO_DIR"
else
    echo "[1/5] KVCache-Factory already cloned, pulling latest..."
    git -C "$REPO_DIR" pull --ff-only
fi

# ── Step 2: Install Python dependencies ────────────────────────────────────────
echo ""
echo "[2/5] Installing Python dependencies..."
cd "$REPO_DIR"
pip install -r requirements.txt -q
# Install the package itself (pyramidkv)
pip install -e . -q
cd ..

# ── Step 3: Install flash-attn ─────────────────────────────────────────────────
echo ""
echo "[3/5] Installing flash-attn (this may take a few minutes)..."
pip install flash-attn --no-build-isolation -q

# ── Step 4: Download LongBench data ───────────────────────────────────────────
echo ""
echo "[4/5] Downloading LongBench data..."
cd "$REPO_DIR"
mkdir -p data/LongBench

DATASETS=(
    narrativeqa qasper multifieldqa_en
    hotpotqa 2wikimqa musique
    gov_report qmsum multi_news
    trec triviaqa samsum
    passage_count passage_retrieval_en
    lcc repobench-p
)

for ds in "${DATASETS[@]}"; do
    FILE="data/LongBench/${ds}.jsonl"
    if [[ ! -f "$FILE" ]]; then
        echo "  Downloading ${ds}..."
        python3 -c "
from datasets import load_dataset
import json, os
ds_name = '${ds}'
data = load_dataset('THUDM/LongBench', ds_name, split='test')
os.makedirs('data/LongBench', exist_ok=True)
with open('data/LongBench/${ds}.jsonl', 'w') as f:
    for item in data:
        f.write(json.dumps(item) + '\n')
print(f'  Written {len(data)} examples for ${ds}')
"
    else
        echo "  ${ds} already downloaded, skipping."
    fi
done
cd ..

# ── Step 5: Verify model path ──────────────────────────────────────────────────
echo ""
echo "[5/5] Verifying model path: $MODEL_PATH"
if [[ ! -d "$MODEL_PATH" ]]; then
    echo "WARNING: Model path does not exist. If using HuggingFace Hub, set MODEL_PATH to the hub id."
    echo "         (e.g., meta-llama/Meta-Llama-3-8B-Instruct)"
else
    echo "  Model directory found."
fi

# ── Write config file for downstream scripts ──────────────────────────────────
CONFIG_FILE="./scripts/config.env"
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by 00_setup.sh — edit as needed
MODEL_PATH="${MODEL_PATH}"
REPO_DIR="$(realpath ./KVCache-Factory)"
RESULTS_DIR="$(realpath ./results)"
ATTN_IMPL="flash_attention_2"    # or "sdpa" for V100/RTX 3090 (no FlashAttn2 support)
EOF

echo ""
echo "======================================================"
echo "  Setup complete!"
echo "  Config saved to: $CONFIG_FILE"
echo ""
echo "  Next step: run scripts/01_run_eval.sh"
echo "======================================================"
